name: Mover archivos modificados a API

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  move-to-api-repo:
    runs-on: ubuntu-latest
    steps:
      # Chequear el código del repositorio principal
      - name: Checkout principal repo
        uses: actions/checkout@v3
        with:
          repository: YoharJB/API
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      # Chequear el código del repositorio API-RAW
      - name: Checkout repo API-RAW
        uses: actions/checkout@v3
        with:
          repository: YoharJB/API-RAW
          token: ${{ secrets.GITHUB_TOKEN }}
          path: API-RAW
          ref: main

      # Obtener los archivos modificados de la PR
      - name: Obtener archivos modificados
        run: |
          # Listar los archivos modificados en la PR
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          echo "Archivos modificados: $(cat changed_files.txt)"

      # Mover los archivos modificados al repositorio API-RAW
      - name: Mover archivos modificados
        run: |
          # Leer cada archivo de la lista de cambios y moverlo
          while IFS= read -r file; do
            # Mover los archivos modificados desde el repositorio principal a API-RAW
            if [[ "$file" == API/Addons/* ]]; then
              mv "./$file" "./API-RAW/$file"
            fi
          done < changed_files.txt

      # Commit de los cambios en el repositorio de API-RAW
      - name: Commit y push cambios
        run: |
          cd API-RAW
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Mover archivos modificados desde la PR"
          git push origin main
